# Generated by Django 4.0.4 on 2022-06-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile_image',
            field=models.ImageField(upload_to='profile_image'),
        ),
    ]
