# Generated by Django 4.0.4 on 2022-06-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='city',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='email',
            field=models.EmailField(max_length=120, null=True, unique=True, verbose_name='Correo Electronico'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='password',
            field=models.CharField(default=123456, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_profile',
            name='user_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='user_is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='profile_image',
            field=models.ImageField(upload_to='profile_image', verbose_name='Imagen de Perfil'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='user',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre de usuario'),
        ),
    ]
