# Generated by Django 4.0.4 on 2022-06-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_profile_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_profile',
        ),
    ]
