# Generated by Django 4.0.4 on 2022-06-23 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_rename_contacto_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
    ]
