# Generated by Django 4.0.4 on 2022-06-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_profile_options_profile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='icono_proyecto.png', upload_to='profile_image'),
        ),
    ]
