# Generated by Django 4.0.4 on 2022-06-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Economia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('publish_date', models.DateField()),
                ('text', models.TextField(blank=True)),
                ('pic', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Salud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('publish_date', models.DateField()),
                ('text', models.TextField(blank=True)),
                ('pic', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='entretenimiento',
            name='name',
        ),
        migrations.AddField(
            model_name='entretenimiento',
            name='pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='entretenimiento',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entretenimiento',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
