# Generated by Django 4.0.4 on 2022-06-03 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_economia_salud_remove_entretenimiento_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='economia',
            options={'verbose_name': 'Economia', 'verbose_name_plural': 'Economia'},
        ),
        migrations.AlterModelOptions(
            name='entretenimiento',
            options={'verbose_name': 'Entretenimiento', 'verbose_name_plural': 'Entretenimiento'},
        ),
        migrations.AlterModelOptions(
            name='salud',
            options={'verbose_name': 'Salud', 'verbose_name_plural': 'Salud'},
        ),
    ]
