# Generated by Django 4.0.4 on 2022-06-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_economia_options_alter_entretenimiento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economia',
            name='pic',
            field=models.ImageField(null=True, upload_to='economia'),
        ),
        migrations.AlterField(
            model_name='entretenimiento',
            name='pic',
            field=models.ImageField(null=True, upload_to='entretenimiento'),
        ),
        migrations.AlterField(
            model_name='salud',
            name='pic',
            field=models.ImageField(null=True, upload_to='salud'),
        ),
    ]
