# Generated by Django 4.0.4 on 2022-06-07 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_about_us'),
    ]

    operations = [
        migrations.DeleteModel(
            name='about_us',
        ),
    ]
