# Generated by Django 4.0.4 on 2022-06-07 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_delete_about_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='economia',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='entretenimiento',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='salud',
            name='pic',
        ),
    ]
