# Generated by Django 4.0.4 on 2022-06-07 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_economia_pic_remove_entretenimiento_pic_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Salud',
            new_name='Economy',
        ),
        migrations.RenameModel(
            old_name='entretenimiento',
            new_name='Entertainment',
        ),
        migrations.RenameModel(
            old_name='Economia',
            new_name='Health',
        ),
        migrations.AlterModelOptions(
            name='economy',
            options={'verbose_name': 'Economia', 'verbose_name_plural': 'Economia'},
        ),
        migrations.AlterModelOptions(
            name='health',
            options={'verbose_name': 'Salud', 'verbose_name_plural': 'Salud'},
        ),
    ]
