# Generated by Django 4.0.4 on 2022-06-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_categoria_note_delete_economy_delete_entertainment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
